version: "2"
run:
  timeout: 3m
  tests: true
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - errcheck
    - staticcheck
    - unused
    - gosec
    - errorlint
issues:
  max-same-issues: 50
