run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive

issues:
  exclude-use-default: false
  max-same-issues: 50
