package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const initTemplate = `# %[1]s — depengine project configuration
# Generated by 'depengine init'
# See: https://github.com/Khorea1/depengine
#
# Commit this file so everyone on the project gets the same tools:
#   git add %[1]s depengine.lock && git commit
# Personal installation knowledge goes in ~/.config/depengine/manifest.toml.

[defaults]
manager = "native"

[tools]
# Tools whose package name is the same on every distro:
simple = [%s]

# Tools with custom package names or language ecosystem managers:
#   fd   = { apt = "fd-find" }
#   fzf  = { go  = "github.com/junegunn/fzf" }
#   ruff = { python = true }
#
# Full docs: https://github.com/Khorea1/depengine#readme
`

var toolNameRegex = regexp.MustCompile(`^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,128}$`)

func runInit(args []string) {
	// flags maintained in help.go:printCommandHelp
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	output := fs.String("schema", "", "path to write (default: schema.toml)")
	addTools := fs.String("add", "", "comma-separated tool names to pre-populate (e.g. 'zsh,bat,nvim')")
	interactive := fs.Bool("interactive", false, "interactive mode: walk through adding tools")
	_ = fs.Parse(args)

	path := *output
	if path == "" {
		path = "schema.toml"
	}

	if *interactive {
		// Don't overwrite existing files.
		if _, err := os.Stat(path); err == nil {
			fmt.Fprintf(os.Stderr, "error: %s already exists\n", path)
			os.Exit(1)
		}
		dir := filepath.Dir(path)
		if dir != "." {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				fmt.Fprintf(os.Stderr, "error: cannot create directory %s: %v\n", dir, err)
				os.Exit(1)
			}
		}
		runInteractiveInit(path)
		return
	}

	// Don't overwrite existing files.
	if _, err := os.Stat(path); err == nil {
		fmt.Fprintf(os.Stderr, "error: %s already exists\n", path)
		os.Exit(1)
	}

	dir := filepath.Dir(path)
	if dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "error: cannot create directory %s: %v\n", dir, err)
			os.Exit(1)
		}
	}

	simpleList := `"tool1", "tool2"`
	if *addTools != "" {
		names := strings.Split(*addTools, ",")
		var quoted []string
		for _, n := range names {
			n = strings.TrimSpace(n)
			if n == "" {
				fmt.Fprintf(os.Stderr, "error: empty tool name (check for doubled commas or trailing comma)\n")
				os.Exit(1)
			}
			if !toolNameRegex.MatchString(n) {
				fmt.Fprintf(os.Stderr, "error: invalid tool name %q: use only letters, digits, underscores, hyphens, and dots\n", n)
				os.Exit(1)
			}
			quoted = append(quoted, fmt.Sprintf("%q", n))
		}
		simpleList = strings.Join(quoted, ", ")
	}

	template := fmt.Sprintf(initTemplate, filepath.Base(path), simpleList)
	if err := os.WriteFile(path, []byte(template), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot write %s: %v\n", path, err)
		os.Exit(1)
	}

	// The ✓ goes to stdout (the created path is the consumable result,
	// pipeable), the hints go to stderr (guidance, not data).
	c := newCLIStyle(os.Stdout)
	msg := fmt.Sprintf("✓ %s created", path)
	if *addTools != "" {
		msg += fmt.Sprintf(" with %d tools", len(strings.Split(*addTools, ",")))
	}
	fmt.Fprintln(c.w, c.green(msg))
	fmt.Fprintln(os.Stderr, "Next: run 'depengine validate' to verify, or 'depengine install' to install.")
	fmt.Fprintln(os.Stderr, "Share this file with your team: git add schema.toml && git commit")
}

// runInteractiveInit runs an interactive wizard that walks the user through
// adding tools to a new schema.toml.
func runInteractiveInit(path string) {
	r := bufio.NewReader(os.Stdin)
	basename := filepath.Base(path)

	fmt.Fprintln(os.Stderr, "depengine init — interactive mode")
	fmt.Fprintln(os.Stderr, "Add tools one by one. Leave name empty to finish.")

	var simpleTools []string
	var customLines []string
	seen := make(map[string]bool)

	for {
		name, err := prompt(r, "Tool name (or empty to finish)")
		if err != nil || name == "" {
			break
		}

		if seen[name] {
			fmt.Fprintf(os.Stderr, "⚠ %q already added. Enter another name.\n", name)
			continue
		}
		seen[name] = true

		fmt.Fprintf(os.Stderr, "\nHow does %s install?\n", name)
		choice, err := promptSelect(r, "Choose method", []string{
			"1) Native — same package name on every distro",
			"2) Native — different name on some distros",
			"3) Cargo (crates.io)",
			"4) Go (pkg.go.dev)",
			"5) Python (pip / pipx / uv)",
			"6) Node (npm / pnpm / bun)",
			"7) Git (clone + build)",
			"8) HTTP (download artifact)",
			"9) Other — skip, I'll edit manually",
		})
		if err != nil {
			break
		}

		switch choice {
		case 0:
			simpleTools = append(simpleTools, name)
		case 1:
			overrides, err := promptMultiMap(r, "Native package overrides (enter names, empty = use tool name)", []string{"pacman", "apt", "brew", "dnf"})
			if err != nil {
				break
			}
			var parts []string
			for _, mgr := range []string{"pacman", "apt", "brew", "dnf"} {
				if v, ok := overrides[mgr]; ok && v != "" {
					parts = append(parts, fmt.Sprintf("%s = %q", mgr, v))
				}
			}
			if len(parts) > 0 {
				customLines = append(customLines, fmt.Sprintf("%s = { %s }", name, strings.Join(parts, ", ")))
			} else {
				simpleTools = append(simpleTools, name)
			}
		case 2:
			// Cargo — ask for crate name if it differs from tool name
			pkg, err := prompt(r, "Crate name (empty if same as tool name)")
			if err != nil {
				break
			}
			if pkg != "" {
				customLines = append(customLines, fmt.Sprintf("%s = { cargo = %q }", name, pkg))
			} else {
				customLines = append(customLines, fmt.Sprintf("%s = { cargo = true }", name))
			}
		case 3:
			// Go
			pkg, err := prompt(r, "Go module path (empty if same as tool name)")
			if err != nil {
				break
			}
			if pkg != "" {
				customLines = append(customLines, fmt.Sprintf("%s = { go = %q }", name, pkg))
			} else {
				customLines = append(customLines, fmt.Sprintf("%s = { go = true }", name))
			}
		case 4:
			customLines = append(customLines, fmt.Sprintf("%s = { python = true }", name))
		case 5:
			customLines = append(customLines, fmt.Sprintf("%s = { node = true }", name))
		case 6:
			url, err := prompt(r, "Git repository URL")
			if err != nil {
				break
			}
			if url == "" {
				url = "true"
			}
			customLines = append(customLines, fmt.Sprintf("%s = { git = %q }", name, url))
		case 7:
			url, err := prompt(r, "Download URL")
			if err != nil {
				break
			}
			if url == "" {
				url = "true"
			}
			customLines = append(customLines, fmt.Sprintf("%s = { http = %q }", name, url))
		case 8:
			customLines = append(customLines, fmt.Sprintf("# %s = {  }  # TODO: configure manually", name))
		}

		fmt.Fprintln(os.Stderr)
	}

	// Build file content
	var b strings.Builder
	b.WriteString(fmt.Sprintf(`# %s — depengine project configuration
# Generated by 'depengine init --interactive'
# See: https://github.com/Khorea1/depengine
#
# Commit this file so everyone on the project gets the same tools:
#   git add %s depengine.lock && git commit
# Personal installation knowledge goes in ~/.config/depengine/manifest.toml.

[defaults]
manager = "native"

[tools]
`, basename, basename))

	if len(simpleTools) > 0 {
		quoted := make([]string, len(simpleTools))
		for i, n := range simpleTools {
			quoted[i] = fmt.Sprintf("%q", n)
		}
		b.WriteString(fmt.Sprintf("simple = [%s]\n", strings.Join(quoted, ", ")))
		if len(customLines) > 0 {
			b.WriteString("\n")
		}
	}

	for _, line := range customLines {
		b.WriteString(line + "\n")
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot write %s: %v\n", path, err)
		os.Exit(1)
	}

	toolCount := len(simpleTools) + len(customLines)
	if toolCount == 0 {
		fmt.Fprintf(os.Stderr, "⚠ %s created — no tools added yet. Edit the file or re-run with --interactive.\n", path)
	} else {
		fmt.Printf("✓ %s created with %d tool(s)\n", path, toolCount)
	}
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "Next: run 'depengine validate' to verify, or 'depengine install' to install.")
	fmt.Fprintln(os.Stderr, "Share this file with your team: git add schema.toml && git commit")
}

// prompt reads a line from stdin, trimming whitespace. Returns io.EOF on Ctrl+D.
func prompt(r *bufio.Reader, msg string) (string, error) {
	fmt.Fprintf(os.Stderr, "%s: ", msg)
	line, err := r.ReadString('\n')
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(line), nil
}

// promptSelect shows a numbered menu and returns the 0-based choice.
func promptSelect(r *bufio.Reader, msg string, options []string) (int, error) {
	for _, opt := range options {
		fmt.Fprintln(os.Stderr, "  "+opt)
	}
	for {
		input, err := prompt(r, msg)
		if err != nil {
			return 0, err
		}
		n, err := strconv.Atoi(input)
		if err != nil || n < 1 || n > len(options) {
			fmt.Fprintf(os.Stderr, "Enter a number between 1 and %d.\n", len(options))
			continue
		}
		return n - 1, nil
	}
}

// promptMultiMap reads values for each key and returns a map of key → value.
// Empty values are omitted from the result.
func promptMultiMap(r *bufio.Reader, msg string, keys []string) (map[string]string, error) {
	fmt.Fprintln(os.Stderr, msg)
	result := make(map[string]string)
	for _, k := range keys {
		v, err := prompt(r, "  "+k)
		if err != nil {
			return nil, err
		}
		if v != "" {
			result[k] = v
		}
	}
	return result, nil
}
