package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

const initTemplate = `# %[1]s — depengine project configuration
# Generated by 'depengine init'
# See: https://github.com/depengine/depengine

[defaults]
# Default package manager for tools without a specific method.
manager = "native"

# AUR helper (only relevant on Arch-based distros).
aur_helper = "paru"

# Method resolution order: the engine tries each until one succeeds.
method_order = ["native", "scoop", "choco", "cargo", "go", "pipx", "uv", "pip", "npm", "pnpm", "bun", "gem", "yarn", "yarn-berry", "composer", "apm", "vscode", "vscodium", "flatpak", "snap", "cask", "mas", "sdkman", "steamcmd", "pacstall", "aur", "conda", "asdf", "git", "http"]

[tools]
# Tools whose package name matches on every distro:
# simple = ["tool1", "tool2"]

# Tools with distro-specific package names:
# fd   = { apt = "fd-find" }
# nvim = { pacman = "neovim", apt = "neovim" }

# Tools from language ecosystems:
# fzf      = { go  = "github.com/junegunn/fzf" }
# ruff     = { python = true }
# prettier = { node = true }

# Tools needing full blocks (multiple methods, hooks, conditions):
# [tools.Example]
# postinstall = "fc-cache -fv"
#   [tools.Example.aur]
#   pkg  = "example-pkg"
#   when = { distro_family = ["arch"] }
#   [tools.Example.http]
#   url = "https://example.com/releases/{latest}/example.tar.gz"
`

func runInit(args []string) {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	output := fs.String("schema", "", "path to write (default: depengine.toml)")
	_ = fs.Parse(args)

	path := *output
	if path == "" {
		path = "depengine.toml"
	}

	// Don't overwrite existing files.
	if _, err := os.Stat(path); err == nil {
		fmt.Fprintf(os.Stderr, "error: %s already exists\n", path)
		os.Exit(1)
	}

	dir := filepath.Dir(path)
	if dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "error: cannot create directory %s: %v\n", dir, err)
			os.Exit(1)
		}
	}

	template := fmt.Sprintf(initTemplate, filepath.Base(path))
	if err := os.WriteFile(path, []byte(template), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot write %s: %v\n", path, err)
		os.Exit(1)
	}

	fmt.Printf("✓ %s created\n", path)
}
