package httpdownload

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/Khorea1/depengine/internal/run"
)

// skipIfNoGPG skips the test if gpg is not available.
func skipIfNoGPG(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("gpg"); err != nil {
		t.Skip("gpg not available, skipping GPG test")
	}
}

// setupGPGDir creates a temporary GNUPGHOME with proper permissions and
// sets the GNUPGHOME environment variable for the test. The homedir is
// created under a short parent: gpg-agent's socket path is derived from
// GNUPGHOME and macOS TMPDIR (/var/folders/...) is deep enough to exceed
// the ~104-char sun_path limit, which makes key generation fail with
// "can't connect to the gpg-agent".
func setupGPGDir(t *testing.T) string {
	t.Helper()
	parent := os.TempDir()
	if runtime.GOOS == "darwin" {
		parent = "/tmp"
	}
	gnupgHome, err := os.MkdirTemp(parent, "depengine-gpg-*")
	if err != nil {
		t.Fatalf("mkdtemp gnupgHome: %v", err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(gnupgHome) })
	if err := os.Chmod(gnupgHome, 0o700); err != nil { // #nosec G302 -- test intentionally changes fixture permissions to exercise permission behavior.
		t.Fatalf("chmod gnupgHome: %v", err)
	}
	// Windows CI ships an MSYS2 gpg (via Git), which reads GNUPGHOME with
	// POSIX semantics: MSYS2 maps the Windows Temp dir onto /tmp, so the
	// native path must be converted for gpg's benefit (cygpath -u yields
	// the /tmp/... spelling of the same directory). Go's own operations
	// above keep the native path — the MSYS spelling is meaningless to
	// native syscalls, and a native-only gpg setup has no cygpath, in
	// which case the native path is exported unchanged.
	envHome := gnupgHome
	if runtime.GOOS == "windows" {
		if out, err := exec.Command("cygpath", "-u", gnupgHome).Output(); err == nil { // #nosec G204 -- test intentionally launches a controlled helper/tool subprocess.
			if s := strings.TrimSpace(string(out)); s != "" {
				envHome = s
			}
		}
	}
	t.Setenv("GNUPGHOME", envHome)
	return gnupgHome
}

// genGPGKey generates a test GPG key with the given email.
func genGPGKey(t *testing.T, keyID string) {
	t.Helper()
	batchInput := "Key-Type: RSA\n" +
		"Key-Length: 2048\n" +
		"Subkey-Type: RSA\n" +
		"Subkey-Length: 2048\n" +
		"Name-Real: GPG Test\n" +
		"Name-Email: " + keyID + "\n" +
		"Expire-Date: 0\n" +
		"%no-protection\n" +
		"%commit\n"

	cmd := exec.Command("gpg", "--batch", "--gen-key")
	cmd.Stdin = strings.NewReader(batchInput)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("gpg --gen-key failed: %v\n%s", err, out)
	}
}

func exportGPGKeyFile(t *testing.T, keyID string) string {
	t.Helper()
	cmd := exec.Command("gpg", "--armor", "--export", keyID) // #nosec G204 -- keyID is generated by this test's temporary GPG home.
	data, err := cmd.Output()
	if err != nil {
		t.Fatalf("gpg --export failed: %v", err)
	}
	path := filepath.Join(t.TempDir(), "pubkey.asc")
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatalf("write public key: %v", err)
	}
	return path
}

func gpgFileURL(path string) string {
	path = filepath.ToSlash(path)
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}
	return "file://" + path
}

// signFile creates an armored detached signature for the given file.
func signFile(t *testing.T, filePath string) string {
	t.Helper()
	cmd := exec.Command("gpg", "--detach-sign", "--armor", "--batch", "--no-tty", filePath) // #nosec G204 -- test intentionally launches a controlled helper/tool subprocess.
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("gpg --detach-sign failed: %v\n%s", err, out)
	}
	sigPath := filePath + ".asc"
	if _, err := os.Stat(sigPath); err != nil {
		t.Fatalf("signature file not created: %v", err)
	}
	return sigPath
}

// TestGPGVerifyValidSignature tests GPG verification with a valid detached
// signature. It creates a temporary GPG keyring, generates a key, signs a
// checksum file, and verifies the signature.
func TestGPGVerifyValidSignature(t *testing.T) {
	skipIfNoGPG(t)
	setupGPGDir(t)
	checksumFile := filepath.Join(t.TempDir(), "checksum.sha256")
	if err := os.WriteFile(checksumFile, []byte("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file.tar.gz\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	genGPGKey(t, "gpgtest@example.com")
	keyFile := exportGPGKeyFile(t, "gpgtest@example.com")
	signatureFile := signFile(t, checksumFile)
	if err := GPGVerify(context.Background(), &run.OSExecRunner{}, checksumFile, signatureFile, gpgFileURL(keyFile)); err != nil {
		t.Fatalf("GPGVerify should accept the configured signer: %v", err)
	}
}

// TestGPGVerifyTamperedFile rejects a checksum file modified after signing.
func TestGPGVerifyTamperedFile(t *testing.T) {
	skipIfNoGPG(t)
	setupGPGDir(t)
	checksumFile := filepath.Join(t.TempDir(), "checksum.sha256")
	if err := os.WriteFile(checksumFile, []byte("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file.tar.gz\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	genGPGKey(t, "gpgtest2@example.com")
	keyFile := exportGPGKeyFile(t, "gpgtest2@example.com")
	signatureFile := signFile(t, checksumFile)
	if err := os.WriteFile(checksumFile, []byte("tampered content\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := GPGVerify(context.Background(), &run.OSExecRunner{}, checksumFile, signatureFile, gpgFileURL(keyFile)); err == nil {
		t.Fatal("GPGVerify should fail on tampered file")
	}
}

// TestGPGVerifyRequiresSigningKey rejects signature checks without an
// explicit signer identity.
func TestGPGVerifyRequiresSigningKey(t *testing.T) {
	fr := &run.FakeRunner{}
	err := GPGVerify(context.Background(), fr, "/checksum", "/signature", " ")
	if err == nil || !strings.Contains(err.Error(), "signing key is required") {
		t.Fatalf("GPGVerify error = %v, want required signer identity", err)
	}
	if len(fr.Calls) != 0 {
		t.Fatalf("GPGVerify ran commands without signer identity: %+v", fr.Calls)
	}
}

// TestGPGVerifyKeyImport verifies that the configured public key is imported
// into an isolated keyring for detached-signature verification.
func TestGPGVerifyKeyImport(t *testing.T) {
	skipIfNoGPG(t)
	setupGPGDir(t)
	checksumFile := filepath.Join(t.TempDir(), "checksum.sha256")
	if err := os.WriteFile(checksumFile, []byte("abc123  test.tar.gz\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	keyID := "gpgtest-keyimport@example.com"
	genGPGKey(t, keyID)
	keyFile := exportGPGKeyFile(t, keyID)
	signatureFile := signFile(t, checksumFile)
	setupGPGDir(t)
	if err := GPGVerify(context.Background(), &run.OSExecRunner{}, checksumFile, signatureFile, gpgFileURL(keyFile)); err != nil {
		t.Fatalf("GPGVerify should import and accept the configured signer: %v", err)
	}
}

// TestGPGVerifyAllExistingPass verifies that checksum verification still works.
func TestGPGVerifyAllExistingPass(t *testing.T) {
	// Just verify the package builds and checksum verification still works.
	content := []byte("hello world")
	tmpFile := filepath.Join(t.TempDir(), "test.txt")
	if err := os.WriteFile(tmpFile, content, 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}

	err := VerifyChecksum(tmpFile, "sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9")
	if err != nil {
		t.Fatalf("VerifyChecksum should pass: %v", err)
	}
}

// TestGPGVerifyWrongSigner verifies that GPGVerify rejects a signature made
// by key B when key A was expected, even when both keys are present in the
// keyring. This test proves the signer-confusion vulnerability is fixed.
func TestGPGVerifyWrongSigner(t *testing.T) {
	skipIfNoGPG(t)
	setupGPGDir(t)

	// Create checksum file.
	checksumContent := []byte("abc123  test.tar.gz\n")
	checksumFile := filepath.Join(t.TempDir(), "checksum.sha256")
	if err := os.WriteFile(checksumFile, checksumContent, 0o600); err != nil {
		t.Fatal(err)
	}

	// Generate signer B and sign with it (B is the only key at signing time).
	genGPGKey(t, "signer-b@example.com")
	sigFile := signFile(t, checksumFile) // signs with B (the default key)

	// Export B's key.
	exportB := exec.Command("gpg", "--armor", "--export", "signer-b@example.com")
	keyDataB, err := exportB.Output()
	if err != nil {
		t.Fatal(err)
	}
	keyFileB := filepath.Join(t.TempDir(), "pubkey-b.asc")
	if err := os.WriteFile(keyFileB, keyDataB, 0o600); err != nil {
		t.Fatal(err)
	}

	// Generate signer A.
	genGPGKey(t, "signer-a@example.com")
	exportA := exec.Command("gpg", "--armor", "--export", "signer-a@example.com")
	keyDataA, err := exportA.Output()
	if err != nil {
		t.Fatal(err)
	}
	keyFileA := filepath.Join(t.TempDir(), "pubkey-a.asc")
	if err := os.WriteFile(keyFileA, keyDataA, 0o600); err != nil {
		t.Fatal(err)
	}

	// Create a combined key file: A's public key first, then B's.
	// extractFingerprintFromKeyFile (called by importSigningKey via --show-key)
	// will return A's fingerprint (the first fpr: line).
	// But the checksum was signed by B. The identity check must catch this.
	combinedKeyFile := filepath.Join(t.TempDir(), "pubkey-combined.asc")
	combined := append([]byte(nil), keyDataA...)
	combined = append(combined, keyDataB...)
	if err := os.WriteFile(combinedKeyFile, combined, 0o600); err != nil {
		t.Fatal(err)
	}

	// Reset GNUPGHOME to a clean dir — no keys pre-imported.
	setupGPGDir(t)

	// Call GPGVerify with the combined key file as signingKey.
	// Before the fix: imports both keys into the shared keyring, verifies B's sig using B's key — passes (BUG).
	// After the fix:  extracts A's fingerprint as expected, imports both into isolated homedir,
	//                 verifies B's sig using B's key — passes crypto check (exit 0),
	//                 then identity comparison fails: expected A, got B.
	rn := &run.OSExecRunner{}
	// Build a well-formed file:// URL: the native path concatenation
	// ("file://" + backslash path) is malformed on Windows; the canonical
	// file:/// form (leading slash, forward separators) parses on both.
	keyURLPath := filepath.ToSlash(combinedKeyFile)
	if !strings.HasPrefix(keyURLPath, "/") {
		keyURLPath = "/" + keyURLPath
	}
	err = GPGVerify(context.Background(), rn, checksumFile, sigFile, "file://"+keyURLPath)
	if err == nil {
		t.Fatal("GPGVerify should fail: signed by key B, expected key A")
	}
	if !strings.Contains(err.Error(), "expected") {
		t.Fatalf("error should mention fingerprint mismatch, got: %v", err)
	}
}
